(defun Sfn (str)
(print '( in Sfn)) (print str)
(cond ((eql (car str)  'a) (Afn (cdr str )))
      ((and (eql (car str) 'b) (eql (cadr str) 'a)) (Bfn (Afn (cddr str))))
      (t (append (cdr str)(list 'err)))))

(defun Afn(str)
 (print '( in Afn)) (print str)
(cond ((eql (car str) 'a) (cond ((eql (Afn (cdr str)) nil)(append (cdr str)(list 'err)))
                                 ((eql (car (Afn (cdr str))) 'b) (cdr (Afn (cdr str))))
                                 (t (append (cdr str)(list 'err))) ))
      ((eql (car str) 'b) (Bfn (cdr str)))
      ((eql (car str) 'c)  (cdr str))
      (t (append (cdr str)(list 'err)))))

(defun Bfn(str)
(print '( in Bfn)) (print str)
(cond ((eql (car str) 'a) (cdr (cdr str)))
      ((eql (car str) 'b) (cond ((eql (Bfn (cdr str)) nil)(append (cdr str)(list 'err)))
                                 ((eql (car (Bfn (cdr str))) 'a) (cdr (Bfn (cdr str))))
                                 (t (append (cdr str)(list 'err))) ) )
      ((eql (car str) 'd)  (cdr str))
      (t (append (cdr str)(list 'err)))))

